version: "3.9"

name: conti_ira_v1

networks:
  mynet:
    driver: bridge
    ipam:
        config:
          - subnet: 172.26.0.0/16
            gateway: 172.26.0.1

volumes:
  ollama:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: "/var/lib/docker/volumes/ollama/_data"
      o: bind    

services:
  conti_ira:
    container_name: conti_ira
    image: mintplexlabs/anythingllm:master
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${UID:-1000}
        ARG_GID: ${GID:-1000}    
    cap_add:
      - SYS_ADMIN
    volumes:
      - "./.env:/app/server/.env"
      - "../server/storage:/app/server/storage"
      - "../collector/hotdir/:/app/collector/hotdir"
      - "../collector/outputs/:/app/collector/outputs"
      - "../agent/:/app/agent"
      - "../frontend/:/app/frontend"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3001:3001"
      - "3002:3002"
      - "11434:11434"  # Map container port 11434 to host port 11435
    env_file:
      - .env
    networks:
      - mynet
    extra_hosts:
      - "host.docker.internal:host-gateway"

  service2:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"  # Map container port 11434 to host port 11436
    volumes:
      - "../ollama:/root/.ollama"
    networks:
      - mynet
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]    
